### ISSUE TITLE
Please delete this post - by some reason got posted twice

### ISSUE THREAD

**Issue by bongobongo** [geofabrik/meta2tile#4] opened 2020-11-04 18:17 UTC
I have compiled meta2tile.c and got it working to make a lot of single tiles from the meta tiles directory. 
But I would like to make an mbtile file. Could someone provide some examples on what syntax to use when running meta2tile to produce mbtile (hopefully without having to change the c code)? After some trail and error - I found some text inside the meta2tile.c file that said one must define WITH_MBTILES 
So then I created a copy of meta2tile.c - named meta2mbtile.c and added: 
#define WITH_MBTILES 
compiled and run it without luck.
then I changed
static int mbtiles = 0
to
static int mbtiles = 1
and now it created an mbtile file without any other input from command line than meta-tile-dir and target file name:
like this:
./meta2mbtile /var/lib/mod_tile/default /media/test/tissd/mbtiles/wz12.db

and then the file reported creating same number of tiles as when creating single tiles. So far so good....
But by some reason the numbering in tile_row column in the wz12.db file is wrong.
zoom_level is set correct to 12
tile_column is set correct from 0 to 4095
tile_row is from 1248 to 3943 - but should have been from 158 to 2847

Is there something else I have to change i the c file to make it work to get the tile_row value (and corresponding tile_data) correct, or even better - if there was some examples on how to use the original file with some parameters when running it from command line - to produce mbtile.

**Comment by bongobongo** [comment] 2020-11-04 18:21
Please just delete this thread -- by some reason I got a 404 error when saving my original question. Then after creating this, I found that my first question was saved after all: Hope to get a response in issue 3:
This: https://github.com/geofabrik/meta2tile/issues/3

**Comment by woodpeck** [comment] 2020-11-04 20:56
Duplicate of #3

**Closed as completed by woodpeck** 2020-11-04 20:56 UTC
